- src/main/resources/com/nulabinc/zxcvbn/messages.properties
Some suggestions used to end with a dot, others didn't.
> Messages punctuation

- src/main/java/com/nulabinc/zxcvbn/Feedback.java
- src/main/java/com/nulabinc/zxcvbn/Scoring.java
- src/main/java/com/nulabinc/zxcvbn/TimeEstimates.java
- src/main/java/com/nulabinc/zxcvbn/guesses/DateGuess.java
- src/main/java/com/nulabinc/zxcvbn/guesses/DictionaryGuess.java
- src/main/java/com/nulabinc/zxcvbn/matchers/DateMatcher.java
- src/main/java/com/nulabinc/zxcvbn/matchers/Dictionary.java
- src/main/java/com/nulabinc/zxcvbn/matchers/SequenceMatcher.java
- src/test/java/com/nulabinc/zxcvbn/ScoringTest.java
Port zxcvbn 4.3.0 and refactor.
> #9 Port zxcvbn 4.3.0

- src/main/java/com/nulabinc/zxcvbn/guesses/BruteforceGuess.java
- src/test/java/com/nulabinc/zxcvbn/MeasureTest.java
Fix:
https://github.com/nulab/zxcvbn4j/issues/19
> add check infinite

- src/main/java/com/nulabinc/zxcvbn/Feedback.java
https://github.com/nulab/zxcvbn4j/issues/21
> fixed ResourceBundle can not be resolved for Android

- src/main/java/com/nulabinc/zxcvbn/TimeEstimates.java
R.S - fixed typo in TimeEstimates.java
> R.S - fixed typo in TimeEstimates.java 

- src/main/java/com/nulabinc/zxcvbn/Scoring.java
- src/main/java/com/nulabinc/zxcvbn/guesses/DateGuess.java
see: https://github.com/dropbox/zxcvbn/releases/tag/v4.4.0
> port zxcvbn v4.4.0

- src/main/java/com/nulabinc/zxcvbn/guesses/BaseGuess.java
- src/main/java/com/nulabinc/zxcvbn/guesses/SpatialGuess.java
- src/main/java/com/nulabinc/zxcvbn/matchers/Keyboard.java
- src/main/java/com/nulabinc/zxcvbn/matchers/SpatialMatcher.java
- src/test/java/com/nulabinc/zxcvbn/JavaPortTest.java
Fixed bug below.
https://github.com/nulab/zxcvbn4j/issues/32
> fix inconsistent keyboard pattern

- .travis.yml
> Switch from OracleJDK7 to OpenJDK7 on Travis-CI

- src/main/java/com/nulabinc/zxcvbn/matchers/Dictionary.java
- src/main/java/com/nulabinc/zxcvbn/matchers/Keyboard.java
- src/main/java/com/nulabinc/zxcvbn/matchers/ResourceLoader.java
I've fixed resource loading when using zxcvbn4j from the Spring web app.
> Fix resource loading when using from the web app.

- src/main/java/com/nulabinc/zxcvbn/matchers/Dictionary.java
replace StandardCharsets to local constant
> remove java.nio.charset.StandardCharsets (#62)

- src/main/resources/com/nulabinc/zxcvbn/messages_de.properties
Hi,
since I needed them anyway, I added a german translation of the messages with correct "umlauts".
> added german translation

- src/main/resources/com/nulabinc/zxcvbn/messages_de.properties
> Fix typo in German translation

- src/main/java/com/nulabinc/zxcvbn/Feedback.java
- src/test/java/com/nulabinc/zxcvbn/FeedbackTest.java
I tried it so that they can insert and replace any ResourceBundle.
I think this will allow us to respect the default message and we can customize it as desired.
> Improved to be able to replace the message arbitrarily

- build.gradle
> Add Automatic-Module-Name to manifest

- src/main/java/com/nulabinc/zxcvbn/matchers/RegexMatcher.java
- src/test/java/com/nulabinc/zxcvbn/FeedbackTest.java
Different from the origin, but added because it is now 2020s
https://github.com/dropbox/zxcvbn/blob/v4.4.2/src/matching.coffee#L38
> fix recent years #100

- build.gradle
fix below
> Could not get unknown property 'mavenJava' for Publication container of type org.gradle.api.publish.internal.DefaultPublicationContainer.
> Change the position of the defining signing (#121)

- build.gradle
- src/test/java/com/nulabinc/zxcvbn/ApproachComparisonTest.java
- src/test/java/com/nulabinc/zxcvbn/JSScriptEngineBuilder.java
- src/test/java/com/nulabinc/zxcvbn/JavaPortTest.java
Switch the JavaScript engine used for testing from Nashorn to GraalJS for the following issue.
https://github.com/nulab/zxcvbn4j/issues/118
> Switch the JavaScript engine used for testing from Nashorn to GraalJS

- README.md
- src/main/resources/com/nulabinc/zxcvbn/messages_es.properties
Spanish is one of the 4 most spoken languages in the world. It may be useful to include it to avoid extra work for others.
Added `messages_es.properties` file to `resources\com\nulabinc\zxcvbn` folder.
Also updated as available language in `README.md`
> Added feedback messages translated into Spanish

- src/main/java/com/nulabinc/zxcvbn/matchers/DictionaryMatcher.java
refactoring matchers. L33tMatcher:
> refactor: refactoring matchers.DictionaryMatcher

- src/main/java/com/nulabinc/zxcvbn/matchers/RepeatMatcher.java
> style: format code in matchers.RepeatMatcher

- src/main/java/com/nulabinc/zxcvbn/matchers/Match.java
refactoring matchers.Match:
- Move initialization process for list fields of matches to the Builder process
> refactor: refactoring matchers.Match

- src/main/java/com/nulabinc/zxcvbn/Optimal.java
- src/main/java/com/nulabinc/zxcvbn/Scoring.java
Refactor and improve code readability in Scoring
- Split overly long methods into smaller, more manageable ones.
- Renamed ambiguous method and variable names for better clarity.
- Extracted Optimal class into its own separate file for better modularity.
> refactor: refactor and improve code readability in Scoring

- .github/workflows/build.yml
- Updated the dependent actions for GitHub Actions.
- Enhanced the Build job in GitHub Actions by adding checkstyle, spotbugs, and google-java-formatter.
> chore: Update GitHub Actions Configuration

- src/main/java/com/nulabinc/zxcvbn/Pattern.java
- src/main/java/com/nulabinc/zxcvbn/StandardDictionaries.java
- src/main/java/com/nulabinc/zxcvbn/StandardKeyboards.java
- src/main/java/com/nulabinc/zxcvbn/WipeableString.java
- src/main/java/com/nulabinc/zxcvbn/io/ClasspathResource.java
- src/main/java/com/nulabinc/zxcvbn/matchers/DateMatcher.java
- Fix code smelts warned by sonar cloud in DateMatcher.
- Corrected the value of SuppressWarnings annotation.
> Fix sonar cloud maintainability phase 2

- src/main/java/com/nulabinc/zxcvbn/Pattern.java
- src/main/java/com/nulabinc/zxcvbn/io/ClasspathResource.java
- src/main/java/com/nulabinc/zxcvbn/matchers/Keyboard.java
- src/main/java/com/nulabinc/zxcvbn/matchers/KeyboardLoader.java
- src/main/java/com/nulabinc/zxcvbn/matchers/L33tSubDict.java
- src/main/java/com/nulabinc/zxcvbn/matchers/Match.java
- src/main/java/com/nulabinc/zxcvbn/matchers/MatchFactory.java
- src/test/java/com/nulabinc/zxcvbn/EdgeCaseTest.java
- src/test/java/com/nulabinc/zxcvbn/MatchingTest.java
- src/test/java/com/nulabinc/zxcvbn/WipeableStringTest.java
- fix the code smell warnings in tests
- fix the code smell warnings in MatchFactory
- fix the code smell warnings in Match
- fix the code smell warnings in L33tSubDict
- fix the code smell warnings in KeyboardLoader
- fix the code smell warnings in Keyboard
- fix the code smell warnings in ClasspathResource
- fix the code smell warnings in Pattern
> fix: fix sonarcloud maintainability phase 3

- src/main/java/com/nulabinc/zxcvbn/matchers/DateMatcher.java
- src/main/java/com/nulabinc/zxcvbn/matchers/DictionaryLoader.java
- fix the code smell warnings in DictionaryLoader
- fix the code smell warnings in DateMatcher
> fix: fix sonarcloud maintainability phase 4

- src/main/java9/module-info.java
> Add exports com.nulabinc.zxcvbn.io to module-info.java
