nulab/zxcvbn4j

src/main/java/com/nulabinc/zxcvbn/Feedback.java, src/main/java/com/nulabinc/zxcvbn/matchers/DictionaryMatcher.java, src/test/java/com/nulabinc/zxcvbn/FeedbackTest.java, src/test/java/com/nulabinc/zxcvbn/MatchingTest.java, src/test/java/com/nulabinc/zxcvbn/MeasureTest.java, src/test/java/com/nulabinc/zxcvbn/ScoringTest.java
1. Introduced Feedback.Message to store a message ID.
2. Added message field to an instance of Feedback, to localise messages on demand.
3. Covered all feedback cases with tests.
4. Moved message IDs to constants to simplify testing.
5. Not sure about new setters of Feedback class. I've updated them just to keep the API. But are the setter really required for this class? I can hardly imagine the use-case. Without them there is no need in the Feedback.Message class.
=> Customisable localisation of Feedback

src/test/java/com/nulabinc/zxcvbn/MatchingTest.java
Static inner class ExpectedMatch was annotated with @org.junit.Ignore.
This broke assumptions of the JUnit4Runner expecting to find a test class
when Gradle tries to enumerate ignored tests. Making it `private` instead of ignoring
solves the problem.
For example, here's the exception in the latest (passing) build: [build 95](https://travis-ci.org/nulab/zxcvbn4j/builds/215534921#L281).
=> Fix the InvocationTargetException when running tests with Gradle

src/main/java/com/nulabinc/zxcvbn/Matching.java, src/main/java/com/nulabinc/zxcvbn/Zxcvbn.java
Change `Zxcvbn` and `Matching` classes to make extending their behavior possible without changing current public API. The main idea is to allow usage of custom (extended) `Matching` class with `Zxcvbn`.
One of possible uses is implementing support for custom user dictionary that is parsed/processed just once and then reused for subsequent calls to `Zxcvbn#measure(String, List<String>)`. Passing large user dictionary to each call of measure causes noticeable slowdown and generates unnecessary GC overhead.
Also includes optimizations avoiding unnecessary allocations for standard use cases.
=>  Improve extensibility of Zxcvbn and Matching and optimize memory usage

.travis.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
TravisCI now doesn't support openjdk7.
Oracle JDK 9 is no longer available.
Upgrade to OpenJDK 12 (current GA).
=> remove openjdk7 from .travis.yml

src/main/java/com/nulabinc/zxcvbn/matchers/Dictionary.java, src/main/java/com/nulabinc/zxcvbn/matchers/Keyboard.java
When this library is obfuscated, loading resources using a relative path might not work anymore (was the case for us). Therefore we had to exclude those classes from being obfuscated. This change uses absolute paths to load resources, so there is no client-side configuration needed to work with code obfuscation tools.
=> Use system class loader to access resources

build.gradle, src/main/java/com/nulabinc/zxcvbn/guesses/DateGuess.java, src/test/java/com/nulabinc/zxcvbn/FeedbackTest.java, src/test/java/com/nulabinc/zxcvbn/JavaPortTest.java
There was a problem with DateGuess.
It needs a null check and an empty character check for the separator.
=> fix inconsistent score between zxcvbn4j and zxcvbn (#50)

src/main/java/com/nulabinc/zxcvbn/matchers/ResourceLoader.java, src/test/java/com/nulabinc/zxcvbn/FeedbackTest.java
ClassLoader might be null, so I added a fallback method based on the Spring Framework implementation.
> Returns the class loader for the class. Some implementations may use null to represent the bootstrap class loader. This method will return null in such implementations if this class was loaded by the bootstrap class loader
- https://docs.oracle.com/javase/6/docs/api/java/lang/Class.html#getClassLoader()
- https://github.com/spring-projects/spring-framework/blob/dfb7ca733ad309b35040e0027fb7a2f10f3a196a/spring-core/src/main/java/org/springframework/util/ClassUtils.java#L173-L210
=> Fix a ExceptionInInitializerError in Keycloak: error found in ResourceLoader #79

src/main/java/com/nulabinc/zxcvbn/matchers/ResourceLoader.java
I added fallback in the process of getting the resource as a stream.
- First, return the InputStream to use: typically the thread context ClassLoader, if available;
- Next, the ClassLoader that loaded the ResourceLoader class will be used as fallback.
- Finally, if even the system ClassLoader could not access resource as stream, return null.
=> fallback in the process of getting the resource as a stream (#79)

src/main/java/com/nulabinc/zxcvbn/Feedback.java, src/test/java/com/nulabinc/zxcvbn/FeedbackTest.java
Fixed formation of a sublist for a method Feedback.getFeedback.
Added tests for checking.
=> Fix Error in method Feedback.getFeedback (#82)

build.gradle
Bump the version of dependencies according to the deps.dev security advisory warnings.
https://deps.dev/maven/com.nulab-inc%3Azxcvbn
=> Bump junit 4.11 to 4.13.2

.github/workflows/build.yml
Nashorn was deprecated in JDK 11. It is now deprecated in JDK 15. Therefore, we are considering using GraalJS to perform the above test in JDK 15.
We have temporarily deprecated the test for JDK 17 at this time. Once the above issues are resolved, we will enable JDK 17 testing.
=> temporarily remove test with JDK 17 (#119)

src/main/java/com/nulabinc/zxcvbn/Scoring.java
=> Make Scoring.factorial(int) return long

build.gradle, src/jmh/java/com/nulabinc/zxcvbn/RandomPasswordMeasureBenchmark.java
Add a JMH-based performance benchmark the same as an already closed PR ( https://github.com/nulab/zxcvbn4j/pull/69 ) to maintain healthy performance.
=> JMH-based set of benchmarks

src/main/java/com/nulabinc/zxcvbn/matchers/RepeatMatcher.java
refactoring matchers.RepeatMatcher:
- Reused the regular expression's Pattern object.
- Reduced the calls to the `group` function in `regex.Matcher`.
=> refactor: refactoring matchers.RepeatMatcher

src/main/java/com/nulabinc/zxcvbn/matchers/BaseMatcher.java, src/main/java/com/nulabinc/zxcvbn/matchers/SpatialMatcher.java
refactoring matchers.SpatialMatcher:
- Removed the redundant `extend` function from `BaseMatcher`.
- Made the regular expression object `shiftedRx` static to reduce the number of times it's created.
- Changed the default `ADJACENTS` to `private static final` to minimize the number of instances created.
- By storing the result of `String.valueOf(charAt)` in a variable and reusing it, the duplication of operations was reduced.
=> refactor: refactoring matchers.SpatialMatcher

build.gradle, src/main/java/com/nulabinc/zxcvbn/Scoring.java, src/main/java/com/nulabinc/zxcvbn/Strength.java, src/main/java/com/nulabinc/zxcvbn/Zxcvbn.java, src/main/java/com/nulabinc/zxcvbn/io/ClasspathResource.java, src/main/java/com/nulabinc/zxcvbn/matchers/BaseMatcher.java, src/main/java/com/nulabinc/zxcvbn/matchers/Keyboard.java
Fixed some low and medium warnings from SpotBugs.
=> fix: fix the warnings from SpotBugs

src/main/java/com/nulabinc/zxcvbn/matchers/SequenceMatcher.java
refactoring matchers.SpatialMatcher:
- Made the regular expression object `LOWERCASE_PATTERN`, `UPPERCASE_PATTERN`, `DIGIT_PATTERN` static to reduce the number of times it's created.
- Defined literal values used in methods and within the class as constants for readability and change management.
- Changed the regular expression's `find` function to `matches` function. (Switched from partial match to a complete match.)
- Defined `SequenceType` as an inner class.
=> refactor: refactoring matchers.SequenceMatcher

src/main/java/com/nulabinc/zxcvbn/matchers/BaseMatcher.java, src/main/java/com/nulabinc/zxcvbn/matchers/L33tMatcher.java
refactoring matchers. L33tMatcher:
- Renamed the `translate` function in `BaseMatcher` to `decodeL33tSpeak` and moved it to `L33tMatcher`.
- Changed type of `L33T_TABLE` to an `UnmodifiableMap`.
- Reduced computational complexity by changing `passwordChars` in the `relevantL33tSubTable` function from `HashMap<Character, Boolean>` to `HashSet<Character>`.
=> refactor: refactoring matchers.L33tMatcher

src/main/java/com/nulabinc/zxcvbn/matchers/RegexMatcher.java
refactoring matchers. L33tMatcher:
- REGEXEN was changed to PATTERNS, and it now holds Pattern objects. This ensures that the pattern is compiled only once, improving performance.
The unnecessary Pattern.compile call inside the loop was removed.
=> refactor: refactoring matchers.RegexMatcher

src/main/java/com/nulabinc/zxcvbn/matchers/DateMatcher.java
refactoring matchers.DateMatcher:
- DATE_SPLITS was converted to an array. With this change, access to DATE_SPLITS is faster, eliminating the need for hash computations and key lookups.
=> refactor: refactoring matchers.DateMatcher

src/main/java/com/nulabinc/zxcvbn/matchers/ReverseDictionaryMatcher.java
refactoring matchers.ReverseDictionaryMatcher:
- Added explanatory variable names.
=> refactor: refactoring matchers.ReverseDictionaryMatcher

src/main/java/com/nulabinc/zxcvbn/matchers/OmnibusMatcher.java
refactoring matchers.OmnibusMatcher:
- The constructor initialized each matcher. This avoids unnecessary initialization process.
=> refactor: refactoring matchers.OmnibusMatcher

src/main/java/com/nulabinc/zxcvbn/Guess.java, src/main/java/com/nulabinc/zxcvbn/matchers/DateMatcher.java, src/test/java/com/nulabinc/zxcvbn/JavaPortTest.java, src/test/java/com/nulabinc/zxcvbn/MatchingTest.java, src/test/java/com/nulabinc/zxcvbn/ScoringTest.java
**Describe the change**
Fix the discrepancy in password guesses between zxcvbn and zxcvbn4j.
**Describe your solution**
- The constant REFERENCE_YEAR was changed to get the current year.
- Fixed the logic of possibleYearSplits in DateMatcher.
**Tests**
- Add DateGuessTest to ScoringTest.
- Add date pattern to MatchingTest.
**Additional context**
Issue: #151
=> fix: fix the discrepancy in password guesses between zxcvbn and zxcvbn4j

src/main/java/com/nulabinc/zxcvbn/guesses/BaseGuess.java, src/main/java/com/nulabinc/zxcvbn/guesses/BruteforceGuess.java, src/main/java/com/nulabinc/zxcvbn/guesses/DateGuess.java, src/main/java/com/nulabinc/zxcvbn/guesses/DictionaryGuess.java, src/main/java/com/nulabinc/zxcvbn/guesses/EstimateGuess.java, src/main/java/com/nulabinc/zxcvbn/guesses/RegexGuess.java, src/main/java/com/nulabinc/zxcvbn/guesses/SequenceGuess.java, src/main/java/com/nulabinc/zxcvbn/guesses/SpatialGuess.java
- optimized pattern matching in uppercaseVariations and reduced lowercaseToken generation in l33tVariations of DictionaryGuess
- clarified exec logic, removed unnecessary else, and improved readability with early returns in RegexGuess
- replaced switch with map lookup, extracted guess initialization, and reduced nesting with early returns in EstimateGuess
- optimized START_POINTS lookup with Set, cached regex pattern, and improved code readability in SequenceGuess
- split the logic inside the exec method of SpatialGuess into two new private methods
- split the logic inside the exec method of DateGuess into two new private methods
- split the logic inside the exec method of BruteforceGuess into two new private methods
- add brackets to the if statement in BaseGuess
=> refactor: refactoring guesses package

src/main/java/com/nulabinc/zxcvbn/TimeEstimates.java
in TimeEstimates:
- define reused values as constants
- streamline displayTime conditions
- simplify format method
=> refactor: refactoring TimeEstimates class

src/main/java/com/nulabinc/zxcvbn/Feedback.java, src/main/java/com/nulabinc/zxcvbn/FeedbackFactory.java
in Feedback class:
- refactor feedback generation using Factory pattern
- refactor error handling in Feedback class for improved readability
=> refactor: Refactoring Feedback

build.gradle, config/checkstyle/checkstyle.xml, config/checkstyle/suppressions-xpath.xml, src/main/java/com/nulabinc/zxcvbn/Scoring.java, src/main/java/com/nulabinc/zxcvbn/TimeEstimates.java, src/main/java/com/nulabinc/zxcvbn/WipeableString.java, src/main/java/com/nulabinc/zxcvbn/guesses/BaseGuess.java, src/main/java/com/nulabinc/zxcvbn/guesses/DictionaryGuess.java, src/main/java/com/nulabinc/zxcvbn/guesses/SpatialGuess.java, src/main/java/com/nulabinc/zxcvbn/io/ClasspathResource.java, src/main/java/com/nulabinc/zxcvbn/matchers/BaseMatcher.java, src/main/java/com/nulabinc/zxcvbn/matchers/DateMatcher.java, src/main/java/com/nulabinc/zxcvbn/matchers/Keyboard.java, src/main/java/com/nulabinc/zxcvbn/matchers/L33tMatcher.java, src/main/java/com/nulabinc/zxcvbn/matchers/RegexMatcher.java, src/test/java/com/nulabinc/zxcvbn/ScoringTest.java
fix warning messages of checkstyle.
=> fix: fix warning messages of checkstyle

src/main/java/com/nulabinc/zxcvbn/Scoring.java, src/main/java/com/nulabinc/zxcvbn/TimeEstimates.java, src/main/java/com/nulabinc/zxcvbn/guesses/DictionaryGuess.java, src/main/java/com/nulabinc/zxcvbn/matchers/L33tMatcher.java
Fix sonarcloud reliability:
- Use another way to initialize this instance in L33tMatcher.
- Cast one of the operands of this subtraction operation to a double in Scoring.
- Use BigDecimal.valueOf instead in TimeEstimates.
- Cast one of the operands of this multiplication operation to a double in DictionaryGuess.
=> fix: Fix sonarcloud reliability

src/main/java/com/nulabinc/zxcvbn/Feedback.java, src/main/java/com/nulabinc/zxcvbn/FeedbackFactory.java, src/main/java/com/nulabinc/zxcvbn/Pattern.java, src/main/java/com/nulabinc/zxcvbn/StandardContext.java, src/main/java/com/nulabinc/zxcvbn/StandardDictionaries.java, src/main/java/com/nulabinc/zxcvbn/StandardKeyboards.java, src/main/java/com/nulabinc/zxcvbn/TimeEstimates.java, src/main/java/com/nulabinc/zxcvbn/WipeableString.java, src/main/java/com/nulabinc/zxcvbn/guesses/DictionaryGuess.java, src/main/java/com/nulabinc/zxcvbn/guesses/EstimateGuess.java, src/main/java/com/nulabinc/zxcvbn/io/ClasspathResource.java
- fix the code smell warnings in ClasspathResource
- fix the code smell warnings in StandardKeyboards
- fix the code smell warnings in StandardDictionaries
- fix the code smell warnings in Pattern
- fix the code smell warnings in EstimateGuess
- fix the code smell warnings in DictionaryGuess
- fix the code smell warnings in WipeableString
- fix the code smell warnings in TimeEstimates
- fix the code smell warnings in StandardContext
- fix the code smell warnings in FeedbackFactory
- fix the code smell warnings in Feedback
=> fix: fix sonarcloud maintainability

src/main/java/com/nulabinc/zxcvbn/MatchSequence.java, src/main/java/com/nulabinc/zxcvbn/Scoring.java, src/main/java/com/nulabinc/zxcvbn/Strength.java, src/main/java/com/nulabinc/zxcvbn/Zxcvbn.java, src/main/java/com/nulabinc/zxcvbn/matchers/RepeatMatcher.java, src/test/java/com/nulabinc/zxcvbn/ScoringTest.java
- Deprecated the default constructor of Strength in favor of initializing all properties through a parameterized constructor.
- Deprecated Scoring's mostGuessableMatchSequence method due to the changes in Strength's initialization.
This change encourages the use of the constructor for setting all properties of the Strength class and discourages partial or post-instantiation modifications.
=> refactor: Initialize all Strength properties via constructor

src/main/java/com/nulabinc/zxcvbn/Matcher.java, src/main/java/com/nulabinc/zxcvbn/matchers/BaseMatcher.java, src/main/java/com/nulabinc/zxcvbn/matchers/Matcher.java, src/main/java/com/nulabinc/zxcvbn/matchers/OmnibusMatcher.java
Deprecate com.nulabinc.zxcvbn.Matcher and introduce new interface in com.nulabinc.zxcvbn.matchers
=> refactor: Deprecate com.nulabinc.zxcvbn.Matcher and introduce new interface in com.nulabinc.zxcvbn.matchers

src/main/java/com/nulabinc/zxcvbn/guesses/BaseGuess.java, src/main/java/com/nulabinc/zxcvbn/guesses/EstimateGuess.java, src/main/java/com/nulabinc/zxcvbn/guesses/Guess.java
Deprecate com.nulabinc.zxcvbn.Guess and introduce new interface in com.nulabinc.zxcvbn.guesses
=> refactor: Deprecate com.nulabinc.zxcvbn.Guess and introduce new interface in com.nulabinc.zxcvbn.guesses

src/main/java/com/nulabinc/zxcvbn/AttackTimes.java
Deprecate setters in CrackTimeSeconds class and CrackTimesDisplay class.
- Marked all setters as deprecated.
- Added recommendation to use constructor for initialization in javadoc.
Deprecate setters in AttackTimes class.
- Marked setters for crackTimeSeconds, crackTimesDisplay, and score as deprecated.
- Added recommendation to use constructor for initialization in javadoc.
=> refactor: Deprecate setters in AttackTimes class

src/main/java/com/nulabinc/zxcvbn/Pattern.java
Modifier 'private' is redundant for enum constructors.
=> refactor: modifier 'private' is redundant for enum constructors
